spring:
  application:
    name: acg-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000  #关闭自我保护，清理间隙10秒
  client:
    register-with-eureka: false #不将自身注册到eureka
    fetch-registry: false #自身不获取服务列表
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/