spring:
  application:
    name: acg-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianyijiuyou/acg-collection.git
          search-paths: /config/**
          username: tianyijiuyou
          password: ENC(ybLvCaI3HCpSwQniT0Ex97I3NFpuLmT4)
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jasypt:
  encryptor:
    password: 24fbd8f6fd4b45e18be93760b2e51f59