spring:
  application:
    name: acg-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tianyijiuyou/acg-collection.git
          force-pull: true
          username: tianyijiuyou
          password: DvHiEJP5bnABtpw
          search-paths: /config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jasypt:
  encryptor:
    password: 24fbd8f6fd4b45e18be93760b2e51f59